TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Controllers/CategoriesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyAspNetCoreApp.Web.Models;

namespace MyAspNetCoreApp.Web.Controllers
{

    [Route("[controller]/[action]")]
    public class CategoriesController : Controller
    {
        private readonly AppDbContext _context;

        public CategoriesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Controllers/ProductsController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using MyAspNetCoreApp.Web.Filters;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;

namespace MyAspNetCoreApp.Web.Controllers;

[Route("[controller]/[action]")]
public class ProductsController : Controller
{
    private readonly IMapper _mapper;
    private readonly AppDbContext _context;
    private readonly IFileProvider _fileProvider;
    
    public ProductsController(AppDbContext context, IMapper mapper, IFileProvider fileProvider)
    {
        _context = context;
        _mapper = mapper;
        _fileProvider = fileProvider;

        _context.SaveChanges();
    }
    // [CacheResourceFilter]
    public IActionResult Index()
    {
        List<ProductViewModel> products = _context.Products.Include(x => x.Category).Select(x => new ProductViewModel()
        {
            Id = x.Id,
            Name = x.Name,
            Price = x.Price,
            Stock = x.Stock,
            CategoryName = x.Category.Name,
            Color = x.Color,
            Description = x.Description,
            Expire = x.Expire,
            ImagePath = x.ImagePath,
            IsPublish = x.IsPublish,
            PublishDate = x.PublishDate

        }).ToList();
        
        return View(products);
    }
    [Route("[controller]/[action]/{productId}", Name = "product")]
    [ServiceFilter(typeof(NotFoundFilter))]
    public IActionResult GetById(int productId)
    {
        var product = _context.Products.Find(productId);

        return View(_mapper.Map<ProductViewModel>(product));
    }
    [Route("[controller]/[action]/{page}/{pageSize}",Name = "productPage")]
    public IActionResult Pages(int page, int pageSize)
    {
        var products = _context.Products.Skip((page - 1) * pageSize).Take(pageSize).ToList();
        
        ViewBag.page = page;
        ViewBag.pageSize = pageSize;
        
        return View(_mapper.Map<List<ProductViewModel>>(products));
    }
    [ServiceFilter(typeof(NotFoundFilter))]
    public IActionResult Remove(int id)
    {
        var product = _context.Products.Find(id);
        _context.Products.Remove(product);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
    public IActionResult Add()
    {
        ViewBag.Expire = new Dictionary<string, int>()
        {
            { "1 Month", 1},
            { "3 Month", 3},
            { "6 Month", 6},
            { "12 Month", 12}
        };

        ViewBag.Color = new SelectList(new List<ColorSelectList>
        {
          new() {Data = "Black", Value = "Black"},  
          new() {Data = "Gray", Value = "Gray"}, 
          new() {Data = "White", Value = "White"}  
        },"Value", "Data");

        var categories = _context.Category.ToList();

        ViewBag.categorySelect = new SelectList(categories, "Id", "Name");

        return View();
    }
    [HttpPost]
    public IActionResult Add(ProductViewModel newProduct)
    {
        IActionResult result = null;
        
        if (ModelState.IsValid)
        {
            try
            {
                var product = _mapper.Map<Product>(newProduct);

                if (newProduct.Image is { Length: > 0 })
                {
                    var root = _fileProvider.GetDirectoryContents("wwwroot");
                    var images = root.First(x => x.Name == "images");
                    var randomImageName = Guid.NewGuid() + Path.GetExtension(newProduct.Image.FileName);
                    var path = Path.Combine(images.PhysicalPath, randomImageName);
                    using var stream = new FileStream(path, FileMode.Create);
                    newProduct.Image.CopyTo(stream);
                
                    product.ImagePath = randomImageName;
                }
                
                _context.Products.Add(product);
                _context.SaveChanges();
                TempData["status"] = "Product has been successfully added";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                // ModelState.AddModelError("error", new ErrorViewModel()
                // {
                //     Errors = new List<string>(){"Problem occurred when saving data, please try again"}
                // }.ToString());
                result = View();
            }
        }
        else
        {
            result = View();
        }

        var categories = _context.Category.ToList();
        ViewBag.categorySelect = new SelectList(categories,"Id", "Name");

        ViewBag.Expire = new Dictionary<string, int>()
        {
            { "1 Month", 1},
            { "3 Month", 3},
            { "6 Month", 6},
            { "12 Month", 12}
        };

        ViewBag.Color = new SelectList(new List<ColorSelectList>
        {
            new() {Data = "Black", Value = "Black"},  
            new() {Data = "Gray", Value = "Gray"}, 
            new() {Data = "White", Value = "White"}  
        },"Value", "Data");

        return result;
    }
    [ServiceFilter(typeof(NotFoundFilter))]
    public IActionResult Update(int id)
    {
        var product = _context.Products.Find(id);
        var categories = _context.Category.ToList();
        
        ViewBag.categorySelect = new SelectList(categories,"Id", "Name",product.CategoryId);


        ViewBag.ExpireValue = product.Expire;
        
        ViewBag.Expire = new Dictionary<string, int>()
        {
            { "1 Month", 1},
            { "3 Month", 3},
            { "6 Month", 6},
            { "12 Month", 12}
        };

        ViewBag.Color = new SelectList(new List<ColorSelectList>
        {
            new() {Data = "Black", Value = "Black"},  
            new() {Data = "Gray", Value = "Gray"}, 
            new() {Data = "White", Value = "White"}  
        },"Value", "Data", product.Color);
        
        return View(_mapper.Map<ProductUpdateViewModel>(product));
    }
    [HttpPost]
    public IActionResult Update(ProductUpdateViewModel updatedProduct)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.ExpireValue = updatedProduct.Expire;
        
            ViewBag.Expire = new Dictionary<string, int>()
            {
                { "1 Month", 1},
                { "3 Month", 3},
                { "6 Month", 6},
                { "12 Month", 12}
            };

            ViewBag.Color = new SelectList(new List<ColorSelectList>
            {
                new() {Data = "Black", Value = "Black"},  
                new() {Data = "Gray", Value = "Gray"}, 
                new() {Data = "White", Value = "White"}  
            },"Value", "Data", updatedProduct.Color);
            
            var categories = _context.Category.ToList();
            
            ViewBag.categorySelect = new SelectList(categories,"Id", "Name",updatedProduct.CategoryId);

            return View();
        }
        if (updatedProduct.Image is { Length: > 0 })
        {
            var root = _fileProvider.GetDirectoryContents("wwwroot");
            var images = root.First(x => x.Name == "images");
            var randomImageName = Guid.NewGuid() + Path.GetExtension(updatedProduct.Image.FileName);
            var path = Path.Combine(images.PhysicalPath, randomImageName);
            using var stream = new FileStream(path, FileMode.Create);
            updatedProduct.Image.CopyTo(stream);
                
            updatedProduct.ImagePath = randomImageName;
        }
        _context.Products.Update(_mapper.Map<Product>(updatedProduct));
        _context.SaveChanges();
        TempData["status"] = "Product has been successfully updated";
        return RedirectToAction("Index");
    }
    [AcceptVerbs("GET", "POST")]
    public IActionResult HasProductName(string name)
    {
        var isProductNameExists = _context.Products.Any(x => x.Name.ToLower() == name.ToLower());

        if (isProductNameExists)
        {
            return Json($"The product with the name {name} has exists. Please try different name for the product.");
        }

        return Json(true);
    }
}

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/ViewComponents/ProductListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;

namespace MyAspNetCoreApp.Web.Views.Shared.ViewComponents;
// [ViewComponent(Name = "p-list")] Changes the tag helper name of the view component
public class ProductListViewComponent : ViewComponent
{
    private readonly AppDbContext _context;

    public ProductListViewComponent(AppDbContext context)
    {
        _context = context;
    }

    public async Task<IViewComponentResult> InvokeAsync(int type=1)
    {
        var viewModels = _context.Products.Select(x => new ProductListComponentViewModel()
        {
            Name = x.Name,
            Description = x.Description
        }).ToList();

        return View(type == 1 ? "Default" : "Type2", viewModels);
    }
}

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/ViewComponents/VisitorViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyAspNetCoreApp.Web.Models;
using MyAspNetCoreApp.Web.ViewModels;

namespace MyAspNetCoreApp.Web.Views.Shared.ViewComponents;

public class VisitorViewComponent : ViewComponent
{
    private readonly AppDbContext _context;
    private readonly IMapper _mapper;

    public VisitorViewComponent(AppDbContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var visitors = _context.Visitors.ToList();
        var visitorsViewModels = _mapper.Map<List<VisitorViewModel>>(visitors);

        ViewBag.visitorsViewModels = visitorsViewModels;
        
        return View();
    }
}

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/LayoutExample.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MyAspNetCoreApp.Web</title>
</head>
<body>
<header>
    <div>
        header
    </div>
    @await RenderSectionAsync("header",false)
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer>
    <div>
        footer
    </div>
        @await RenderSectionAsync("footer",false)
</footer>
</body>
</html>

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/_FooterPartialView.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MyAspNetCoreApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/_HeaderPartialView.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyAspNetCoreApp.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>
                     <li class="nav-item"> 
                         <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a> 
                     </li> 
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Visitor">Visitors</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MyAspNetCoreApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MyAspNetCoreApp.Web.styles.css" asp-append-version="true"/>
    @await RenderSectionAsync("Css", required: false)
</head>
<body>
<partial name="_HeaderPartialView"/>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<partial name="_FooterPartialView"/>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/globalize/globalize.js"></script>
    <script src="~/Scripts/globalize/cultures/globalize.culture.@(System.Threading.Thread.CurrentThread.CurrentCulture.Name).js"></script>
    <script>
    $.validator.methods.number = function (value, element) {
        return this.optional(element) ||
            !isNaN(Globalize.parseFloat(value));
    }
    $(document).ready(function () {
        Globalize.culture('@(System.Threading.Thread.CurrentThread.CurrentCulture.Name)');
    });
</script>
    <script>
    jQuery.extend(jQuery.validator.methods, {
        range: function (value, element, param) {
            //Use the Globalization plugin to parse the value
            var val = Globalize.parseFloat(value);
            return this.optional(element) || (
                val >= param[0] && val <= param[1]);
        }
    });
    $.validator.methods.date = function (value, element) {
        return this.optional(element) ||
            Globalize.parseDate(value) ||
            Globalize.parseDate(value, "yyyy-MM-dd");
    }
</script>
}

TurkcellBootcamp/Camp_401/MyAspNetCoreApp/MyAspNetCoreApp.Web/Views/Shared/_MenuPartialView.cshtml
<ul>
    <li>Categories</li>
    <li>About Us</li>
    <li>Gallery</li>
</ul>